name: Build the website

on:
  push:
    branches:
      - main   # Triggers workflow on push to the main branch
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Quarto
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      # Step 3: Install R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      # Step 4: Install R dependencies
      - name: Install R dependencies using renv
        uses: r-lib/actions/setup-renv@v2
       
      # Step 5: Publish website
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
